version: '3.1'
services:
  webapp:
    container_name: store-web
    restart: always
    image: store-web
    ports:
      - 3001:80
    build:
      context: ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock