name: marketplace_store_web
description: marketplace web
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular:
  mobx:
  flutter_mobx:
  flutter_svg:
  intl:
  another_flushbar:
  google_fonts:
  localstorage:
  dio:
  font_awesome_flutter:
  flutter_masked_text2:
  auto_size_text_pk:
  grouped_list:
  timelines:
  image_picker:
  jwt_decode:
  shared_preferences:
  location:
  geolocator:
  geocode:
  rxdart:
  timeline:
  responsive: 0.3.9+9



dependency_overrides:


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  flutter_modular_test: ^1.0.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
analyzer:
  enable-experiment:
    - non-nullable

scripts:
  mobx: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs

  #slidy g m modules/delivery/modules/delivery  & slidy g mbx modules/client/modules/delivery/delivery  & slidy g p modules/client/modules/delivery/delivery

  #slidy g m modules/client  & slidy g mbx modules/client/client  & slidy g p modules/client/client