name: marketplace_store_web
description: marketplace web
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.2.1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_svg:
  intl:
  another_flushbar:
  google_fonts:
  localstorage:
  dio:
  responsive:
  flutter_icons:
  flutter_masked_text:
  auto_size_text:
  grouped_list:
  timelines:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  flutter_modular_test: ^1.0.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

scripts:
  mobx: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs

  #slidy g m modules/client/modules/cart  & slidy g mbx modules/client/modules/cart/cart  & slidy g p modules/client/modules/cart/cart

  #slidy g m modules/client  & slidy g mbx modules/client/client  & slidy g p modules/client/client